# Generated by Django 5.2.1 on 2025-06-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылочное имя')),
            ],
            options={
                'verbose_name': 'Группа мышц',
                'verbose_name_plural': 'Группы мышц',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_muscle_name_63facb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SingleMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылочное имя')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='main.musclegroup', verbose_name='Группа мышц')),
            ],
            options={
                'verbose_name': 'Мышца',
                'verbose_name_plural': 'Мышцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылочное имя')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_type_name_0cda9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, upload_to='exercises', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Ссылочное имя')),
                ('video_link', models.URLField(blank=True, unique=True, verbose_name='Ссылка на видео')),
                ('muscles', models.ManyToManyField(to='main.singlemuscle', verbose_name='Задействованные мышцы')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.type', verbose_name='Тип упражнения')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='singlemuscle',
            index=models.Index(fields=['name'], name='main_single_name_77e977_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['id', 'slug'], name='main_exerci_id_0c37ef_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='main_exerci_name_ea34af_idx'),
        ),
    ]
