# Generated by Django 5.2.1 on 2025-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ссылочное имя'),
        ),
    ]
