# Generated by Django 5.2.1 on 2025-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
