# Generated by Django 5.2.1 on 2025-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0002_alter_user_options_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='main.exercise', verbose_name='Любимые'),
        ),
    ]
